""" update categories table

Revision ID: 65abbf618b56
Revises: bdc6059e87fa
Create Date: 2025-01-19 23:46:53.110508

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65abbf618b56"
down_revision: Union[str, None] = "bdc6059e87fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories", sa.Column("model_path", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("categories", "model_path")
    # ### end Alembic commands ###
